### ISSUE TITLE
Typo in "3. Point to example.com"

### ISSUE THREAD

**Issue by jasonflorentino** [jvns/mess-with-dns#15]
In the last section of the "Why do I get a 404 error?" explanation, the first bullet says `Type example.com into your browser` when it should say `Type bad-ip.[subdomain].messwithdns.com into your browser`. 

![Screen Shot 2021-12-21 at 2 11 45 PM](https://user-images.githubusercontent.com/72258481/146985049-cc64a679-2a6e-48d4-99ce-9da25dd8f698.png)

**Comment by jvns** [comment]
Thank you!
