### ISSUE TITLE
Typo in "3. See how CNAME records work"

### ISSUE THREAD

**Issue by bantic** [jvns/mess-with-dns#17]
In step 2 the CNAME is created for "fruit", not "orange", so I think the text here should be mentioning "fruit" as well.

![image](https://user-images.githubusercontent.com/2023/147453698-d490ec7b-7ab5-4bc7-acd8-de2228ac4db1.png)

Thanks for creating this very cool tool!

**Comment by jvns** [comment]
Fixed, thanks!
