### ISSUE TITLE
SRV RRs priority and weight can't be set to 0

### ISSUE THREAD

**Issue by x0ul** [jvns/mess-with-dns#18]
This is probably a front-end issue but this seems the be the place to report it. Basically, I think the bounds checking on the priority and weight fields of a SRV resource record is incorrect. I tried to make an SRV record with values of 0 for both priority and weight and got this red text:

> Priority must be between 0 and 65535.
> Weight must be between 0 and 65535.

[RFC 2782](https://datatracker.ietf.org/doc/html/rfc2782) defines the SRV record type and says (bottom of page 3):

>   Priority
>        The priority of this target host.  A client MUST attempt to
>        contact the target host with the lowest-numbered priority it can
>        reach; target hosts with the same priority SHOULD be tried in an
>        order defined by the weight field.  The range is 0-65535.  This
>        is a 16 bit unsigned integer in network byte order.
>
>   Weight
>        A server selection mechanism.  The weight field specifies a
>        relative weight for entries with the same priority. Larger
>        weights SHOULD be given a proportionately higher probability of
>        being selected. The range of this number is 0-65535.  This is a
>        16 bit unsigned integer in network byte order.  Domain
>        administrators SHOULD use Weight 0 when there isn't any server
>        selection to do, to make the RR easier to read for humans (less
>        noisy).  In the presence of records containing weights greater
>        than 0, records with weight 0 should have a very small chance of
>        being selected.

So I think 0 should be allowed. Also, I checked 65535 and get the same red text, so that should be allowed too.

Thanks!

**Comment by jvns** [comment]
Thanks, just fixed this and added a test for it.
