### ISSUE TITLE
Targets/Nameservers are flagged invalid when containing a dash "-"

### ISSUE THREAD

**Issue by lyuzashi** [jvns/mess-with-dns#22]
![Screen Shot 2022-02-02 at 4 09 36 pm](https://user-images.githubusercontent.com/802833/152096699-9a9adeed-038c-4f47-9e8b-6d61f8cac917.png)

These are valid domains, but cannot be submitted

**Comment by blewandowski-appfire** [comment]
I run into the same issue

**Comment by jvns** [comment]
Finally fixed this! (and added a test for it in 5d466c4)
