### ISSUE TITLE
Add support for SVCB/HTTPS records

### ISSUE THREAD

**Issue by tfpauly** [jvns/mess-with-dns#23]
SVCB/HTTPS records are nearing RFC status, and are being deployed more widely:

https://www.ietf.org/archive/id/draft-ietf-dnsop-svcb-https-08.html

Building in support for these types would be very cool and useful!

**Comment by quaintdev** [comment]
I actually wanted to learn more about DNS after I learned about SVCB records.  I remembered Julia had written about how DNS works so I went there and found out about messwithdns. I am so glad that something like this exists!

Very few DNS providers support SVCB records at the moment. I wanted to experiment with it but unfortunately I could not find an easy way to do it. I was half expecting messwithdns to support SVCB/HTTPS record but was not surprised as these specs are very new. I think it will be a game changer and messwithdns should support it. Thanks @jvns for your work. Highly appreciate it.

**Comment by jvns** [comment]
Thanks for suggesting this -- I just added SVCB/HTTPS record support in 527cbe61c1bd9dcec9330c69b3c29f97afaf22e9, please open an issue if you see problems with it! I wasn't able to test it that well because I'm not very familiar with those record types.
