### ISSUE TITLE
Fastmail example

### ISSUE THREAD

**Issue by PrernaWeb** [jvns/mess-with-dns#26]
Cannot sign up to Fastmail using the generated domain. Fastmail requires a domain to be registered first?
![image](https://user-images.githubusercontent.com/19397253/167439129-a2edafa2-2b73-4491-967c-cefc86dce430.png)

**Comment by jvns** [comment]
Thanks for reporting, I'm not sure how to fix this but I added a note in 4a7f59da5be5fad55626d87ebaf4e1957c138902 saying that the instructions may not work.
