### ISSUE TITLE
Can't create a CNAME record beginning with a "_"

### ISSUE THREAD

**Issue by remyd74** [jvns/mess-with-dns#31]
You couldn't create a CNAME record begin with a "_"
![image](https://github.com/jvns/mess-with-dns-backend/assets/83014185/da210205-8b57-44db-8807-68a9b9cf68d8)

**Comment by jvns** [comment]
Thanks -- I believe this is fixed now, and added a test for it in 452f5de6666edc8967877543ca2c646e9bccb41e
