### ISSUE TITLE
Requests Tracker doesn't show requests from https://dns-lookup.jvns.ca/

### ISSUE THREAD

**Issue by florian-re** [jvns/mess-with-dns#33]
Not sure if this is a bug, or if it is intended like it is, but I just noticed that DNS queries that are initiated by usage of the site https://dns-lookup.jvns.ca/ do not show up in the requests tracker on messwithdns.
Not even on a completely fresh subdomain with only one A record and the first DNS query I myself initiated is a "Get me all record types" on the website shows any requests.
If you want to check - the record is [dfwreed.herb223.messwithdns.com]
I've not made any other checks than using the "all records" button for this name on https://dns-lookup.jvns.ca/

**Comment by jvns** [comment]
This is working for me now, but feel free to reopen if it's still broken for you!
